### ISSUE TITLE
Your scripts only works for Text app and won't function in commmand line tool

### ISSUE THREAD

**Issue by yiakwy** [kermit666/dotfiles#1]
I d'on't know wether you have tested it in CL environment, but it does not work. According to your codes,  "ctrl+c" is shortcut of copy in Text App. However, you didn't show how to map global copy (copy files, copy text, copy photos ...) into a hotkey.

You were using a different log file from the Linux autokey-gtk app, hence no output should auto.log can see. Another problem is that I don't understand why you send_key("<alt>+c").

The "copy" here means copy function in global system. Contents will be kept in registers.

**Comment by metakermit** [comment]
hey @yiakwy thanks for reporting. Yeah, I honestly haven't been using these scripts on Linux for a while now. Lots has probably changed in GNOME since then. I'm mostly using this repo to keep my Atom / zsh / etc. configs synchronised.

**Comment by metakermit** [comment]
I updated the README a bit to reflect that I'm not really sure the autokey stuff will work that well any more.
