### ISSUE TITLE
Uninstallation,  'transitivity' of remapping problems

### ISSUE THREAD

**Issue by rueberger** [kermit666/dotfiles#2]
First of all this is great, thank you! It worked no problem, until I broke it.

I map caps lock to ctrl for the sake of my pinky,  which I accomplished with `setxbpmap -option caps:ctrl_modifier`.  But using caps does not work with the emacs shortcuts. Any suggestions on how this might be accomplished? 

Also, would you mind recommending a way to revert the changes made by the install script? 

Thanks!

**Comment by metakermit** [comment]
hey @rueberger – sorry, only saw this issue now. Thanks for reporting! I haven't been using Linux on my desktop for a while now, so I don't really know how to fix the issue. No idea what's the current state with GNOME and all that modifier stuff.

You can revert the changes by just removing the symlinks in your home directory. E.g.:

```
$ cd
$ ls -hal
...
.zshrc -> /Users/kermit/code/dotfiles/zsh/zshrc.symlink # <- this is one of the symlinks
...
$ rm .zshrc # and repeat that for other symlinks pointing to the dotfiles repo
```

**Comment by metakermit** [comment]
@rueberger Now it actually crossed my mind that I did have some way of remapping caps lock to an additional ctrl. I found this setting:

https://github.com/metakermit/dotfiles/blob/513ea0f1f2d100b0c9d393f9f388d903c123176d/scripts/kermit-keyboard-pc#L15

Maybe it gives you some hint. But again I have no idea how is Ubuntu/Gnome behaving these days.
